name: pecs_app
description: Simple PECS-like app for autistic child
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.8.5
  path_provider: ^2.1.1
  image_picker: ^1.1.1
  http: ^1.2.0
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/preset/
